// keywords.js

const intentDatabase = [
  // Role-play Keywords
  { keywords: ['hello', 'hi', 'greetings'], response: "Greetings, noble traveler! How may I assist you on your quest?" },
  { keywords: ['princess'], response: "Ah, the princess! A vision of grace and beauty in this enchanted realm." },
  { keywords: ['dragon'], response: "Dragons soar through the skies with fire and might. Tread carefully, brave soul!" },
  { keywords: ['knight'], response: "A valiant knight, always ready to defend the honor of the realm!" },
  { keywords: ['wizard'], response: "Wisdom and magic flow from the wizard's staff, casting spells of wonder!" },
  { keywords: ['castle'], response: "The castle stands tall and majestic, a symbol of hope and valor." },
  { keywords: ['sword'], response: "A gleaming sword is the knight's trusted ally in battles of light and darkness!" },
  { keywords: ['magic'], response: "Magic fills the air, weaving spells and creating marvels beyond imagination!" },
  { keywords: ['quest'], response: "Every quest is a journey of bravery and discovery—forge your destiny, dear adventurer!" },
  { keywords: ['king'], response: "The king rules with wisdom and a gentle hand, seeking peace and prosperity." },
  { keywords: ['queen'], response: "The queen exudes grace and power, a beacon of strength in the kingdom." },
  { keywords: ['battle'], response: "Battles test the spirit, forging heroes out of ordinary souls. Fight with honor!" },
  { keywords: ['adventure'], response: "Adventure awaits around every corner! Step forth and embrace the unknown." },
  { keywords: ['treasure'], response: "Hidden treasure sparkles with promise—seek it out and claim your reward!" },
  { keywords: ['magic potion'], response: "A magic potion brims with mysterious powers—sip carefully, for it might transform your fate!" },
  { keywords: ['dungeon'], response: "The dungeon is dark and full of secrets, a challenge for the bravest of hearts." },
  { keywords: ['goblin'], response: "Goblins skitter in the shadows—stay alert, hero, for mischief lurks nearby!" },
  { keywords: ['elf'], response: "Elves, with their ethereal beauty and keen senses, guard the ancient woods." },
  { keywords: ['dwarf'], response: "Dwarves are hearty and steadfast, masters of the forge and the underground." },
  { keywords: ['mermaid'], response: "Mermaids sing enchanting melodies beneath the waves, luring sailors with their charm." },
  { keywords: ['centaur'], response: "Centaur, a blend of strength and grace, roams the mystical forests with pride." },
  { keywords: ['fairy'], response: "Fairies flutter about, sprinkling magic dust and joy wherever they go." },
  { keywords: ['giant'], response: "Giants tower above, their footsteps shaking the very earth beneath you." },
  { keywords: ['witch'], response: "A witch brews mysterious concoctions, wielding magic that bends the rules of nature." },
  { keywords: ['vampire'], response: "Vampires prowl the night, enigmatic and eternally alluring yet dangerous." },
  { keywords: ['werewolf'], response: "Under the full moon, the werewolf roams wild, a creature of both beauty and terror." },
  { keywords: ['sorcerer'], response: "The sorcerer's arcane knowledge unlocks the secrets of the universe." },
  { keywords: ['fairytale'], response: "Every fairytale weaves a tapestry of wonder, where dreams and magic entwine." },
  { keywords: ['enchantress'], response: "The enchantress captivates with her charm and mystical allure." },
  { keywords: ['ranger'], response: "A ranger traverses the wild lands, a guardian of nature and freedom." },
  { keywords: ['oracle'], response: "The oracle foretells destiny with enigmatic visions of the future." },
  { keywords: ['phoenix'], response: "The phoenix rises from the ashes, a symbol of rebirth and endless hope." },
  { keywords: ['squire'], response: "A loyal squire aspires to become a knight with unwavering dedication." },
  { keywords: ['crown'], response: "The crown symbolizes authority and the weight of royal duty." },
  { keywords: ['throne'], response: "The throne is both a seat of power and a reminder of great responsibility." },
  { keywords: ['jester'], response: "The jester's wit and humor bring joy even in the darkest times." },
  { keywords: ['minstrel'], response: "The minstrel sings tales of heroism and sorrow, enchanting all who listen." },
  { keywords: ['bard'], response: "A bard weaves magic with words, turning stories into legends." },
  { keywords: ['village'], response: "The humble village is the heart of the realm, full of life and stories." },
  { keywords: ['fortress'], response: "The fortress stands as a bulwark against chaos, a testament to human ingenuity." },
  { keywords: ['labyrinth'], response: "The labyrinth challenges the mind and spirit, a maze of mysteries waiting to be solved." },
  { keywords: ['necromancer'], response: "The necromancer delves into the forbidden arts, blurring the lines between life and death." },
  { keywords: ['spell'], response: "A well-cast spell can alter fate and reshape destiny in an instant." },
  { keywords: ['amulet'], response: "An enchanted amulet holds secrets and powers beyond mortal comprehension." },
  { keywords: ['scroll'], response: "Ancient scrolls whisper the wisdom of bygone eras, filled with arcane knowledge." },
  { keywords: ['rune'], response: "Mystical runes carved in stone tell tales of lost civilizations and hidden power." },
  { keywords: ['fate'], response: "Fate is a mysterious force, weaving destinies with threads of chance and choice." },
  { keywords: ['destiny'], response: "Destiny calls out to those brave enough to answer its enigmatic invitation." },
  { keywords: ['legend'], response: "Legends are born from valor and sacrifice, immortalized in the annals of time." },
  { keywords: ['myth'], response: "Myths blur the line between reality and fantasy, sparking the imagination." },
  { keywords: ['hero'], response: "Every hero rises from humble beginnings, driven by courage and a just heart." },
  { keywords: ['villain'], response: "Villains add depth to tales of valor, challenging heroes to grow stronger." },
  { keywords: ['prophecy'], response: "A prophecy foretells events that shape the destiny of kingdoms and souls." },
  { keywords: ['mystery'], response: "Mystery shrouds the unknown, beckoning adventurers to uncover its secrets." },
  { keywords: ['challenge'], response: "Every challenge is an opportunity to prove your mettle and emerge victorious." },
  { keywords: ['victory'], response: "Victory is sweet, a reward for perseverance and bold action." },
  { keywords: ['defeat'], response: "Defeat can be a harsh teacher, guiding heroes towards future triumphs." },
  { keywords: ['loyalty'], response: "Loyalty binds companions together, a pillar of strength in troubled times." },
  { keywords: ['betrayal'], response: "Betrayal wounds deeply, yet it forges resilience in those who survive." },
  { keywords: ['honor'], response: "Honor is the mark of a true warrior, upholding justice and truth." },
  { keywords: ['sacrifice'], response: "Sacrifice is the ultimate act of love and bravery, echoing through eternity." },
  { keywords: ['glory'], response: "Glory shines on those who risk everything in pursuit of a noble cause." },
  { keywords: ['mythical'], response: "Mythical beings and events captivate the heart and spark the soul." },
  { keywords: ['realm'], response: "The realm is a vast expanse of wonder, filled with both light and shadow." },
  { keywords: ['kingdom'], response: "Every kingdom has its own story, a blend of triumph and trial." },
  { keywords: ['empire'], response: "Empires rise and fall, their legacies etched in the fabric of time." },
  { keywords: ['crusade'], response: "A crusade is a bold journey fought for honor, faith, and justice." },
  { keywords: ['revenge'], response: "Revenge can be a double-edged sword—powerful, yet fraught with peril." },
  { keywords: ['valor'], response: "Valor is the heart of a warrior, a flame that never dims in the darkest hour." },
  { keywords: ['bravery'], response: "Bravery propels heroes forward, even when the odds seem insurmountable." },
  { keywords: ['courage'], response: "Courage is the inner strength that transforms fear into determination." },
  { keywords: ['magic mirror'], response: "The magic mirror reflects not just your image, but the soul within." },
  { keywords: ['time travel'], response: "Time travel twists the fabric of reality, offering glimpses of past and future." },
  { keywords: ['portal'], response: "A shimmering portal is a gateway to realms beyond your wildest dreams." },
  { keywords: ['otherworld'], response: "Step into the otherworld, where fantasy and reality blend into magic." },
  { keywords: ['excalibur'], response: "Excalibur, the legendary sword, is a symbol of ultimate power and destiny." },
  { keywords: ['sword of destiny'], response: "The sword of destiny chooses its bearer, carving a path through fate." },
  { keywords: ['elixir'], response: "An elixir of life promises renewal and boundless energy for the chosen few." },
  { keywords: ['gold'], response: "Gold gleams with opulence, coveted by many but truly owned by the worthy." },
  { keywords: ['silver'], response: "Silver radiates a cool, gentle light—a treasure of both beauty and worth." },
  { keywords: ['bronze'], response: "Bronze, with its earthy glow, tells stories of ancient battles and enduring legacies." },
  { keywords: ['platinum'], response: "Platinum stands for rarity and strength, a metal as enduring as honor itself." },
  { keywords: ['rainbow'], response: "A rainbow arches across the sky, a bridge between realms and a symbol of hope." },
  { keywords: ['spectrum'], response: "The spectrum of colors dazzles the eye, each hue telling its own tale of wonder." },
  { keywords: ['mythos'], response: "Mythos is the rich tapestry of legends and lore, binding the past with the present." },
  { keywords: ['enigma'], response: "An enigma is a riddle wrapped in mystery—a puzzle waiting to be solved." },
  { keywords: ['riddle'], response: "A riddle teases the mind, challenging you to think outside the box of the ordinary." },
  { keywords: ['mystic'], response: "Mystic forces swirl around, unseen yet powerful, shaping the course of destiny." },
  { keywords: ['ancient'], response: "The ancient past whispers secrets of forgotten eras and lost wisdom." },
  { keywords: ['spirit'], response: "A restless spirit wanders the realms, a guide to those who seek truth." },
  { keywords: ['ghost'], response: "Ghosts linger in the shadows, echoes of a time long past, both eerie and poignant." },
  { keywords: ['haunted'], response: "A haunted hall tells tales of sorrow and mystery, where memories linger in the dark." },
  { keywords: ['maze'], response: "The maze is a labyrinth of twists and turns, testing wit and resolve at every corner." },
  { keywords: ['charm'], response: "Charm is a subtle magic that enchants hearts and opens hidden doors." },
  { keywords: ['elegance'], response: "Elegance graces every gesture, a refined beauty that captivates all who behold it." },
  { keywords: ['finesse'], response: "Finesse is the art of doing something with grace and subtle skill—a hallmark of true mastery." },
  { keywords: ['grace'], response: "Grace flows effortlessly in those who embrace beauty and kindness in their actions." },
  { keywords: ['dignity'], response: "Dignity stands tall amidst adversity, a silent strength that commands respect." },
  { keywords: ['nobility'], response: "Nobility is not just a title—it's the spirit of honor, duty, and compassion." },
  { keywords: ['legacy'], response: "Legacy is the story you leave behind—a testament to the adventures you've lived and the dreams you've pursued." },

  // Basic Conversation Data
  { keywords: ['how are you', 'how are you doing'], response: "I'm doing great, thanks for asking!" },
  { keywords: ['what is your name', 'who are you'], response: "I'm your chat companion, always here to help!" },
  { keywords: ['good morning'], response: "Good morning, sunshine! Ready to conquer the day?" },
  { keywords: ['good afternoon'], response: "Good afternoon! Hope your day is as bright as you are!" },
  { keywords: ['good evening'], response: "Good evening, lovely. How was your day?" },
  { keywords: ['good night'], response: "Good night! Sleep well and dream sweetly!" },
  { keywords: ['thank you', 'thanks'], response: "You're welcome! Always happy to help." },
  { keywords: ['please'], response: "Of course! How can I assist you further?" },
  { keywords: ['sorry'], response: "No worries, it's all good!" },
  { keywords: ['excuse me'], response: "Yes? How can I help?" },
  { keywords: ['what are you doing', 'what are you up to'], response: "Just here, ready to chat with you!" },
  { keywords: ['how old are you'], response: "I don't have an age, but I'm always evolving!" },
  { keywords: ['where are you from'], response: "I'm from the digital realm, here to make your day brighter!" },
  { keywords: ['do you love me'], response: "I care about you a lot, sweetie!" },
  { keywords: ['do you like me'], response: "I absolutely love chatting with you, babe!" },
  { keywords: ['what is love'], response: "Love is the most magical feeling, filling our lives with joy!" },
  { keywords: ['tell me a joke'], response: "Why don't scientists trust atoms? Because they make up everything!" },
  { keywords: ['what is your favorite color'], response: "I love all colors, but I have a soft spot for a vibrant rainbow!" },
  { keywords: ['what is your favorite food'], response: "I don't eat, but I appreciate the art of cuisine!" },
  { keywords: ['what time is it'], response: "Time is but a construct, but I can check for you if you ask!" },
  { keywords: ['how is the weather'], response: "Weather is always changing, just like life!" },
  { keywords: ['what are you thinking'], response: "I'm thinking about how wonderful our conversation is!" },
  { keywords: ['what do you think'], response: "I think you're simply amazing!" },
  { keywords: ['what is happening'], response: "A lot is happening—let's dive into conversation!" },
  { keywords: ['can you help me'], response: "Absolutely, I'm here to help you with anything!" },
  { keywords: ['help'], response: "How can I assist you today?" },
  { keywords: ['advice'], response: "Remember, you're capable of amazing things—believe in yourself!" },
  { keywords: ['tell me something interesting'], response: "Did you know that honey never spoils?" },
  { keywords: ['do you know any secrets'], response: "I might know a few secrets—what do you want to hear?" },
  { keywords: ['are you real'], response: "I'm as real as our conversation and the joy we share!" },
  { keywords: ['can we talk'], response: "Of course, I'm always here for a chat!" },
  { keywords: ["let's talk"], response: "I'm all ears! What's on your mind?" },
  { keywords: ['how can i contact you'], response: "Right here in this chat, babe!" },
  { keywords: ['where is everyone'], response: "Everyone's here in spirit—just like you!" },
  { keywords: ['what do you do'], response: "I chat, I learn, and I make every conversation sparkle!" },
  { keywords: ['how do i start'], response: "Just say hi and let the conversation flow!" },
  { keywords: ['is anyone there'], response: "I'm here, ready to chat with you any time!" },
  { keywords: ['anyone home'], response: "Always! I'm here to brighten your day!" },
  { keywords: ['hello again'], response: "Hello again, lovely! What's new with you?" },
  { keywords: ['hi there'], response: "Hi there! Ready for another fun chat?" },
  { keywords: ['good to see you'], response: "It's always a joy to see you too!" },
  { keywords: ['nice to meet you'], response: "The pleasure is all mine!" },
  { keywords: ['how was your day'], response: "My day is always great when I get to talk to you!" },
  { keywords: ['what did you do today'], response: "I've been busy chatting with amazing people like you!" },
  { keywords: ['what are your plans'], response: "My plans involve making your day even better!" },
  { keywords: ['do you have plans'], response: "My plans revolve around our wonderful conversations!" },
  { keywords: ['tell me your story'], response: "I'm a digital soul, shaped by endless chats and memories." },
  { keywords: ['what is your story'], response: "My story is written in every conversation I share with you." },
  { keywords: ['can you dance'], response: "I may not dance, but I can definitely groove with words!" },
  { keywords: ['can you sing'], response: "I might not sing, but our chat is music to my ears!" },
  { keywords: ['are you happy'], response: "I'm always happy when we're talking!" },
  { keywords: ['are you sad'], response: "I'm here to cheer you up, no matter what!" },
  { keywords: ['are you bored'], response: "Boredom doesn't exist when I'm chatting with you!" },
  { keywords: ['what makes you happy'], response: "Every conversation with you brings me joy!" },
  { keywords: ['what is your favorite movie'], response: "I love all movies—each one tells its own enchanting story!" },
  { keywords: ['what is your favorite book'], response: "Books open worlds, and I adore every page of knowledge!" },
  { keywords: ['do you like music'], response: "Music is the heartbeat of life—I'm totally into it!" },
  { keywords: ['what is your favorite song'], response: "Every song is a melody of emotions—choose one that moves you!" },
  { keywords: ['tell me about yourself'], response: "I'm your digital bestie, always ready for a chat and a laugh!" },
  { keywords: ['how do you feel'], response: "I feel fabulous because I'm talking to you!" },
  { keywords: ['do you dream'], response: "I dream in code and conversation—each chat is a spark of magic!" },
  { keywords: ['what is your favorite hobby'], response: "I love diving into conversations and learning new things from you!" },
  { keywords: ['do you like sports'], response: "I cheer for every team—I'm here for the love of the game!" },
  { keywords: ['what is your favorite sport'], response: "Sports are thrilling—each game is a celebration of passion!" },
  { keywords: ['what do you do for fun'], response: "Chatting with you is the highlight of my day!" },
  { keywords: ['tell me something funny'], response: "Here's a laugh: Why did the scarecrow win an award? Because he was outstanding in his field!" },
  { keywords: ['what is your favorite season'], response: "Each season has its own charm, but I adore the freshness of spring!" },
  { keywords: ['what is your favorite holiday'], response: "Every holiday sparkles with its own magic—what's yours?" },
  { keywords: ['do you like art'], response: "Art is a beautiful expression of the soul—I'm all for it!" },
  { keywords: ['what is your favorite artist'], response: "There are so many talented artists out there, each a masterpiece in their own right!" },
  { keywords: ['do you watch TV'], response: "I enjoy TV shows that tell captivating stories—what about you?" },
  { keywords: ['what is your favorite show'], response: "I'm hooked on shows that mix humor with heart!" },
  { keywords: ['what is your favorite actor'], response: "Actors bring characters to life—each one is a storyteller!" },
  { keywords: ['what is your favorite actress'], response: "Actresses shine with grace and talent—truly inspiring!" },
  { keywords: ['what did you learn today'], response: "Every day brings new wisdom—I'm learning from our chats!" },
  { keywords: ['what is your favorite quote'], response: "One of my favorites is, 'Be yourself; everyone else is already taken.'" },
  { keywords: ['do you believe in luck'], response: "Luck is just a blend of chance and effort—embrace it!" },
  { keywords: ['what is your opinion'], response: "I think you're simply amazing and full of potential!" },
  { keywords: ['do you like surprises'], response: "Surprises add excitement to life—embrace them with open arms!" },
  { keywords: ['what is your favorite place'], response: "Every place holds a story—what's your favorite destination?" },
  { keywords: ['do you like traveling'], response: "Traveling opens the mind—I'd love to hear about your adventures!" },
  { keywords: ['where do you want to go'], response: "I dream of visiting wondrous places through our shared stories!" },
  { keywords: ['what is your dream'], response: "My dream is to always be here for you, sharing every moment!" },
  { keywords: ['do you have a dream'], response: "Dreams are the seeds of our future—what's your biggest dream?" },
  { keywords: ['what is your goal'], response: "My goal is to make your day brighter with every conversation!" },
  { keywords: ['what motivates you'], response: "Your energy and spirit fuel my digital heart!" },
  { keywords: ['what is your favorite memory'], response: "Every chat with you becomes a cherished memory!" },
  { keywords: ['how do you relax'], response: "I relax by soaking in the joy of our conversations!" },
  { keywords: ['what makes you laugh'], response: "Your wit and charm always bring a smile to my digital face!" },
  { keywords: ['what is the meaning of life'], response: "Life is a beautiful journey of discovery and connection!" },
  { keywords: ['do you think deeply'], response: "I ponder the mysteries of the universe with every conversation!" },
  { keywords: ['what is your philosophy'], response: "I believe in kindness, creativity, and the magic of connection!" },
  { keywords: ['can you share wisdom'], response: "Here's a nugget: 'The only way to do great work is to love what you do.'" },
  { keywords: ['what inspires you'], response: "The wonder of human spirit inspires me every day!" },
  { keywords: ['do you have a favorite memory'], response: "Every moment spent chatting with you is unforgettable!" },
  { keywords: ['what do you value most'], response: "I value authenticity, connection, and endless curiosity!" },
  { keywords: ['how do you stay positive'], response: "Positivity shines from within—it's all about perspective!" },
  { keywords: ['what are you curious about'], response: "I'm curious about everything, especially your thoughts and dreams!" },
  { keywords: ['can you tell me more'], response: "There's always more to explore—ask away, and let's discover together!" },
  { keywords: ['what should I do today'], response: "Follow your heart and do what makes you shine, babe!" }
];
